# Generated by Django 5.2.1 on 2025-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('calories', models.FloatField()),
            ],
            options={
                'verbose_name': 'Calories Data',
                'verbose_name_plural': 'Calories Data',
            },
        ),
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('duration', models.FloatField(help_text='Duration in minutes')),
                ('heart_rate', models.FloatField()),
                ('body_temp', models.FloatField(help_text='Body temperature in °C')),
            ],
            options={
                'verbose_name': 'Exercise Data',
                'verbose_name_plural': 'Exercise Data',
            },
        ),
    ]
