# Generated by Django 5.2.1 on 2025-05-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('random_forest', 'Random Forest'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM')], max_length=20, unique=True)),
                ('file', models.FileField(upload_to='models/')),
                ('mse', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('feature_importances', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
