# Generated by Django 5.2.1 on 2025-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_trainedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='name',
            field=models.CharField(choices=[('linear_regression', 'Linear Regression'), ('random_forest', 'Random Forest'), ('xgboost', 'XGBoost')], max_length=20, unique=True),
        ),
    ]
